NAME=		autoconf
PKGNAMESUFFIX=	263
VERSION=	2.63
DESC=		GNU Autoconf
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DIST_SITE=	http://ftp.gnu.org/gnu/autoconf/

BUILD_DEPENDS=	devel:m4

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
