NAME=		sqlite
VERSION=	3.6.22
DESC=		SQLite
ARCHES=		sparc i386
CATEGORY=	databases
MAINTAINER=	ports@solports.org
BASEDIR=	/usr/local

DISTNAME=	${NAME}-amalgamation-${VERSION}
DIST_SITE=	http://sqlite.org/

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
