NAME=		sqlite
VERSION=	3.6.14.2
DESC=		SQLite
ARCHES=		sparc i386
CATEGORY=	databases
MAINTAINER=	ports@solports.org
BASEDIR=	/usr/local

#DISTNAME=	$(NAME)-amalgamation-$(VERSION)$(EXTRACT_SUFX)
DIST_SITE=	http://sqlite.org/

HAS_CONFIGURE=	yes

include ../../Makefile.common
