NAME=		pixman
VERSION=	0.15.12
DESC=		Pixel Manipulation Library
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DIST_SITE=	http://xorg.freedesktop.org/releases/individual/

HAS_CONFIGURE=	yes

include ../../Makefile.common
