NAME=		libtool
VERSION=	2.2.6b
DESC=		GNU Portable Library Tool
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DIST_SITE=	http://ftp.gnu.org/gnu/$(NAME)/

HAS_CONFIGURE=	yes

include ../../Makefile.common
