NAME=		zsh
VERSION=	4.2.7
DESC=		The Z Shell
ARCHES=		sparc i386
CATEGORY=	editors
MAINTAINER=	james@netinertia.co.uk
BASEDIR=	/usr/local

DIST_SITE=	http://kent.dl.sourceforge.net/sourceforge/zsh/${DISTNAME}

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
