NAME=		automake
PKGNAMESUFFIX=	111
VERSION=	1.11
DESC=		GNU Automake
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DIST_SITE=	http://ftp.gnu.org/gnu/automake/

BUILD_DEPENDS=	devel:autoconf263

HAS_CONFIGURE=	yes

include ../../Makefile.common
