NAME=		setuptools
VERSION=	0.6c11
DESC=		Setuptools
ARCHES=		sparc i386
CATEGORY=	devel
MAINTAINER=	jamesog@solports.org
BASEDIR=	/usr/local

DIST_SITE=	http://pypi.python.org/packages/source/s/$(NAME)/

include ../../Makefile.common
