NAME=		libevent
VERSION=	1.4.11
DESC=		GNU Portable Library Tool
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DISTNAME=	$(NAME)-$(VERSION)-stable$(EXTRACT_SUFX)
WRKSRC=		$(WRKDIR)/$(NAME)-$(VERSION)-stable

HAS_CONFIGURE=	yes

include ../../Makefile.common
