NAME=		base
VERSION=	1.4.3.1
DESC=		Basic Analysis and Security Engine
ARCHES=		sparc i386
CATEGORY=	security
MAINTAINER=	james@netinertia.co.uk
BASEDIR=	/usr/local

RUN_DEPENDS=	lang:php5 databases:adodb graphics:pear-Image_Graph \
		mail:pear-Mail_Mime

.include "../../Mk/port.mk"
