NAME=		ntop
VERSION=	3.3.10
DESC=		Network Top
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

BUILD_DEPENDS=	databases:rrdtool databases:gdbm devel:libevent

HAS_CONFIGURE=	yes
CONFIGURE_SCRIPT=autogen.sh

.include "../../Mk/port.mk"
