NAME=		libxslt
VERSION=	1.1.26
DESC=		The XSLT C Library
ARCHES=		sparc i386
CATEGORY=	textproc
BASEDIR=	/usr/local

DIST_SITE=	ftp://xmlsoft.org/libxml2/

BUILD_DEPENDS=	textproc:libxml2

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
