#!/sbin/sh

# If removing from a filesystem that is not running the OS, exit this script.
if [ ! x"$PKG_INSTALL_ROOT" = x"" ] ; then exit 0 ; fi

# Stop BIND if it is running.
# If removing from a non-global zone, the service may still be
# installed/running.  Errors are ignored if nothing is done.
smf=no
if [ -f /usr/sbin/svccfg -a -f /usr/sbin/svcadm ] ;
then smf=yes ; fi

if [ $smf = yes ]
then
   # Disable service
   /usr/sbin/svcadm disable -s svc:/network/dns-server:bind96 >/dev/null 2>&1
   # Unregister with SMF
   /usr/sbin/svccfg delete svc:/network/dns-server:bind96 >/dev/null 2>&1
fi

exit 0
