NAME=		automake
PKGNAMESUFFIX=	110
VERSION=	1.10.2
DESC=		GNU Automake
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

BUILD_DEPENDS=	devel:autoconf263

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
