NAME=		gd
VERSION=	2.0.35
DESC=		GD Graphics Library
ARCH=		sparc
CATEGORY=	application
VENDOR=		http://www.libgd.org packaged for MHCB
BASEDIR=	/usr/local

HAS_CONFIGURE=	true

include ../../Makefile.common
