NAME=		vim
VERSION=	7.2
DESC=		Vi IMproved
ARCHES=		sparc i386
CATEGORY=	editors
MAINTAINER=	jamesog@solports.org
BASEDIR=	/usr/local

EXTRACT_SUFX=	.tar.bz2
WRKSRC=		$(WRKDIR)/$(NAME)$(subst .,,$(VERSION))

DIST_SITE=	ftp://ftp.vim.org/pub/vim/unix/$(DISTNAME)

HAS_CONFIGURE=	yes

include ../../Makefile.common
