NAME=		vim
VERSION=	7.2
DESC=		Vi IMproved
ARCHES=		sparc i386
CATEGORY=	editors
MAINTAINER=	james@netinertia.co.uk
BASEDIR=	/usr/local

EXTRACT_SUFX=	.tar.bz2
WRKSRC=		${WRKDIR}/${NAME}${VERSION:S/.//}

DIST_SITE=	ftp://ftp.vim.org/pub/vim/unix/${DISTNAME}

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
