NAME=		zlib
VERSION=	1.2.3
DESC=		zlib compression library
ARCH=		sparc
CATEGORY=	application
BASEDIR=	/usr/local

HAS_CONFIGURE=	true
CONFIGURE_ARGS=	--shared --prefix=${PREFIX}
DESTDIRNAME=	prefix
FAKE_PREFIX=	${WRKINST}${PREFIX}

.include "../../Mk/port.mk"
