NAME=		expat
VERSION=	2.0.1
DESC=		XML Parser
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DIST_SITE=	http://downloads.sourceforge.net/project/expat/expat/$(VERSION)/

HAS_CONFIGURE=	yes

include ../../Makefile.common
