NAME=		cairo
VERSION=	1.8.8
DESC=		Cairo Graphics Library
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

BUILD_DEPENDS=	graphics:png print:freetype x11:pixman x11:fontconfig

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
