NAME=		png
VERSION=	1.4.3
DESC=		PNG Reference Library
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DISTNAME=	lib${NAME}-${VERSION}
DIST_SITE=	http://download.sourceforge.net/libpng/

WRKSRC=		${WRKDIR}/lib${NAME}-${VERSION}

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
