NAME=		png
VERSION=	1.2.37
DESC=		PNG Reference Library
ARCHES=		sparc
CATEGORY=	net
BASEDIR=	/usr/local

DISTNAME=	lib$(NAME)-$(VERSION)$(EXTRACT_SUFX)
WRKSRC=		$(WRKDIR)/lib$(NAME)-$(VERSION)

HAS_CONFIGURE=	yes

include ../../Makefile.common
