NAME=		bash
VERSION=	4.0
DESC=		Bourne Again SHell
ARCHES=		sparc i386
CATEGORY=	editors
MAINTAINER=	james@netinertia.co.uk
BASEDIR=	/usr/local

DIST_SITE=	http://ftp.gnu.org/gnu/bash/

HAS_CONFIGURE=	yes

.include "../../Mk/port.mk"
