NAME=		bash
VERSION=	4.0
DESC=		Bourne Again SHell
ARCHES=		sparc i386
CATEGORY=	editors
MAINTAINER=	jamesog@solports.org
BASEDIR=	/usr/local

#WRKSRC=		$(WRKDIR)/$(NAME)$(subst .,,$(VERSION))

DIST_SITE=	http://ftp.gnu.org/gnu/bash/$(DISTNAME)

HAS_CONFIGURE=	yes

include ../../Makefile.common
